# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtail_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtTail(object):
    def setupUi(self, QtTail):
        QtTail.setObjectName("QtTail")
        QtTail.resize(719, 507)
        self.centralwidget = QtWidgets.QWidget(QtTail)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.followCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.followCheck.setObjectName("followCheck")
        self.horizontalLayout.addWidget(self.followCheck)
        self.reloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout.addWidget(self.reloadButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.searchTerm = QtWidgets.QLineEdit(self.centralwidget)
        self.searchTerm.setClearButtonEnabled(True)
        self.searchTerm.setObjectName("searchTerm")
        self.horizontalLayout.addWidget(self.searchTerm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = myBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(100, 100))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        QtTail.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QtTail)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 16))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        QtTail.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QtTail)
        self.statusbar.setObjectName("statusbar")
        QtTail.setStatusBar(self.statusbar)
        self.actionAdjust = QtWidgets.QAction(QtTail)
        self.actionAdjust.setObjectName("actionAdjust")
        self.actionCount_lines = QtWidgets.QAction(QtTail)
        self.actionCount_lines.setObjectName("actionCount_lines")
        self.actionWrap_lines = QtWidgets.QAction(QtTail)
        self.actionWrap_lines.setCheckable(True)
        self.actionWrap_lines.setChecked(True)
        self.actionWrap_lines.setObjectName("actionWrap_lines")
        self.actionFont = QtWidgets.QAction(QtTail)
        self.actionFont.setObjectName("actionFont")
        self.actionWatch = QtWidgets.QAction(QtTail)
        self.actionWatch.setCheckable(True)
        self.actionWatch.setObjectName("actionWatch")
        self.actionAutorefresh = QtWidgets.QAction(QtTail)
        self.actionAutorefresh.setCheckable(True)
        self.actionAutorefresh.setObjectName("actionAutorefresh")
        self.actionFontMono = QtWidgets.QAction(QtTail)
        self.actionFontMono.setObjectName("actionFontMono")
        self.actionFontMono_2 = QtWidgets.QAction(QtTail)
        self.actionFontMono_2.setObjectName("actionFontMono_2")
        self.menuView.addAction(self.actionAdjust)
        self.menuView.addAction(self.actionCount_lines)
        self.menuView.addAction(self.actionWrap_lines)
        self.menuView.addAction(self.actionFont)
        self.menuMode.addAction(self.actionWatch)
        self.menuMode.addAction(self.actionAutorefresh)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.label.setBuddy(self.searchTerm)

        self.retranslateUi(QtTail)
        self.searchTerm.textChanged['QString'].connect(QtTail.simpleFindNew) # type: ignore
        self.reloadButton.clicked.connect(QtTail.reload) # type: ignore
        self.searchTerm.returnPressed.connect(QtTail.simpleFind2) # type: ignore
        self.actionAdjust.triggered.connect(QtTail.actionAdjust) # type: ignore
        self.actionCount_lines.triggered.connect(QtTail.showsize) # type: ignore
        self.actionCount_lines.triggered.connect(QtTail.showsize) # type: ignore
        self.actionWrap_lines.triggered['bool'].connect(QtTail.wrapChanged) # type: ignore
        self.followCheck.toggled['bool'].connect(self.textBrowser.jumpToEndMaybe) # type: ignore
        self.actionFont.triggered.connect(self.textBrowser.pickFont) # type: ignore
        self.actionAutorefresh.triggered.connect(QtTail.actionAutoRefresh) # type: ignore
        self.actionWatch.triggered.connect(QtTail.setButtonMode) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QtTail)

    def retranslateUi(self, QtTail):
        _translate = QtCore.QCoreApplication.translate
        QtTail.setWindowTitle(_translate("QtTail", "qtail"))
        self.followCheck.setText(_translate("QtTail", "Follow"))
        self.reloadButton.setText(_translate("QtTail", "Reload"))
        self.label.setText(_translate("QtTail", "Search:"))
        self.menuView.setTitle(_translate("QtTail", "View"))
        self.menuMode.setTitle(_translate("QtTail", "Mode"))
        self.actionAdjust.setText(_translate("QtTail", "Adjust"))
        self.actionAdjust.setToolTip(_translate("QtTail", "Adjust size"))
        self.actionCount_lines.setText(_translate("QtTail", "Count lines"))
        self.actionWrap_lines.setText(_translate("QtTail", "Wrap lines"))
        self.actionFont.setText(_translate("QtTail", "Pick font"))
        self.actionWatch.setText(_translate("QtTail", "Watch"))
        self.actionAutorefresh.setText(_translate("QtTail", "Autorefresh"))
        self.actionFontMono.setText(_translate("QtTail", "Pick monospace font"))
        self.actionFontMono_2.setText(_translate("QtTail", "Pick monospaced font"))
from qtailbrowser import myBrowser
