# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableviewer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableViewer(object):
    def setupUi(self, TableViewer):
        TableViewer.setObjectName("TableViewer")
        TableViewer.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableViewer.sizePolicy().hasHeightForWidth())
        TableViewer.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(TableViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 674, 542))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        TableViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TableViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 16))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        TableViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TableViewer)
        self.statusbar.setObjectName("statusbar")
        TableViewer.setStatusBar(self.statusbar)
        self.colPickerDock = QtWidgets.QDockWidget(TableViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colPickerDock.sizePolicy().hasHeightForWidth())
        self.colPickerDock.setSizePolicy(sizePolicy)
        self.colPickerDock.setObjectName("colPickerDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hideButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.hideButton.setObjectName("hideButton")
        self.horizontalLayout.addWidget(self.hideButton)
        self.showButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.showButton.setObjectName("showButton")
        self.horizontalLayout.addWidget(self.showButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.colPicker = QtWidgets.QListView(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colPicker.sizePolicy().hasHeightForWidth())
        self.colPicker.setSizePolicy(sizePolicy)
        self.colPicker.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.colPicker.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.colPicker.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.colPicker.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.colPicker.setResizeMode(QtWidgets.QListView.Adjust)
        self.colPicker.setObjectName("colPicker")
        self.verticalLayout.addWidget(self.colPicker)
        self.colPickerDock.setWidget(self.dockWidgetContents)
        TableViewer.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.colPickerDock)
        self.actionAdjust_size = QtWidgets.QAction(TableViewer)
        self.actionAdjust_size.setObjectName("actionAdjust_size")
        self.actionColumn_picker = QtWidgets.QAction(TableViewer)
        self.actionColumn_picker.setCheckable(True)
        self.actionColumn_picker.setObjectName("actionColumn_picker")
        self.actionShow_line_numbers = QtWidgets.QAction(TableViewer)
        self.actionShow_line_numbers.setCheckable(True)
        self.actionShow_line_numbers.setObjectName("actionShow_line_numbers")
        self.actionResize_rows = QtWidgets.QAction(TableViewer)
        self.actionResize_rows.setObjectName("actionResize_rows")
        self.actionShow_headings = QtWidgets.QAction(TableViewer)
        self.actionShow_headings.setCheckable(True)
        self.actionShow_headings.setChecked(True)
        self.actionShow_headings.setObjectName("actionShow_headings")
        self.actionResize_window = QtWidgets.QAction(TableViewer)
        self.actionResize_window.setObjectName("actionResize_window")
        self.actionSqueeze_columns = QtWidgets.QAction(TableViewer)
        self.actionSqueeze_columns.setObjectName("actionSqueeze_columns")
        self.actionUse_numerical_headings = QtWidgets.QAction(TableViewer)
        self.actionUse_numerical_headings.setCheckable(True)
        self.actionUse_numerical_headings.setObjectName("actionUse_numerical_headings")
        self.menuView.addAction(self.actionAdjust_size)
        self.menuView.addAction(self.actionResize_window)
        self.menuView.addAction(self.actionResize_rows)
        self.menuView.addAction(self.actionSqueeze_columns)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShow_headings)
        self.menuView.addAction(self.actionUse_numerical_headings)
        self.menuView.addAction(self.actionShow_line_numbers)
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(TableViewer)
        self.actionAdjust_size.triggered.connect(TableViewer.actionAdjust) # type: ignore
        self.hideButton.clicked.connect(TableViewer.hideCols) # type: ignore
        self.showButton.clicked.connect(TableViewer.showCols) # type: ignore
        self.actionResize_rows.triggered.connect(self.tableView.resizeRowsToContents) # type: ignore
        self.actionShow_line_numbers.triggered['bool'].connect(TableViewer.showRowNumbers) # type: ignore
        self.actionShow_headings.toggled['bool'].connect(TableViewer.showHeadings) # type: ignore
        self.actionResize_window.triggered.connect(TableViewer.resizeWindowToTable) # type: ignore
        self.actionSqueeze_columns.triggered.connect(TableViewer.squeezeColumns) # type: ignore
        self.actionUse_numerical_headings.toggled['bool'].connect(TableViewer.numberHeadings) # type: ignore
        self.tableView.clicked['QModelIndex'].connect(TableViewer.copyClip1) # type: ignore
        self.tableView.doubleClicked['QModelIndex'].connect(TableViewer.copyClip2) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TableViewer)

    def retranslateUi(self, TableViewer):
        _translate = QtCore.QCoreApplication.translate
        TableViewer.setWindowTitle(_translate("TableViewer", "MainWindow"))
        self.menuView.setTitle(_translate("TableViewer", "View"))
        self.colPickerDock.setWindowTitle(_translate("TableViewer", "Column Picker"))
        self.hideButton.setText(_translate("TableViewer", "hide"))
        self.showButton.setText(_translate("TableViewer", "show"))
        self.actionAdjust_size.setText(_translate("TableViewer", "Adjust size"))
        self.actionColumn_picker.setText(_translate("TableViewer", "Column picker"))
        self.actionShow_line_numbers.setText(_translate("TableViewer", "Show line numbers"))
        self.actionResize_rows.setText(_translate("TableViewer", "Resize rows vertically"))
        self.actionShow_headings.setText(_translate("TableViewer", "Show headings"))
        self.actionResize_window.setText(_translate("TableViewer", "Resize window"))
        self.actionSqueeze_columns.setText(_translate("TableViewer", "Squeeze columns"))
        self.actionUse_numerical_headings.setText(_translate("TableViewer", "Use numerical headings"))
