# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/colorlisteditor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_colorListEditor(object):
    def setupUi(self, colorListEditor):
        colorListEditor.setObjectName("colorListEditor")
        colorListEditor.resize(373, 270)
        colorListEditor.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(colorListEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(colorListEditor)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(colorListEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(colorListEditor)
        self.buttonBox.accepted.connect(colorListEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(colorListEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(colorListEditor)

    def retranslateUi(self, colorListEditor):
        _translate = QtCore.QCoreApplication.translate
        colorListEditor.setWindowTitle(_translate("colorListEditor", "Color list editor"))
        self.listWidget.setSortingEnabled(True)
