# Form implementation generated from reading ui file 'lib/searchdock_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_searchDock(object):
    def setupUi(self, searchDock):
        searchDock.setObjectName("searchDock")
        searchDock.resize(299, 549)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showButton = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.showButton.setObjectName("showButton")
        self.horizontalLayout.addWidget(self.showButton)
        self.hideButton = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.hideButton.setObjectName("hideButton")
        self.horizontalLayout.addWidget(self.hideButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(parent=self.dockWidgetContents)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.tableView.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.tableView.setWordWrap(False)
        self.tableView.setCornerButtonEnabled(False)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        searchDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(searchDock)
        QtCore.QMetaObject.connectSlotsByName(searchDock)

    def retranslateUi(self, searchDock):
        _translate = QtCore.QCoreApplication.translate
        searchDock.setWindowTitle(_translate("searchDock", "DockWidget"))
        self.showButton.setText(_translate("searchDock", "show"))
        self.hideButton.setText(_translate("searchDock", "hide"))
